version: "3.9"

services:
  backend:
    build: .
    container_name: express_ts_app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
